config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create]

  resources :questions do
    resources :answers, except: %i[new show]
  end
  root 'pages#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence:true, length: {minimum: 5}

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  validates :title, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 2}

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :set_question!
  before_action :set_answer!, except: :create

  def update
    if @answer.update answer_params
      flash[:success] = "Answer updated!"
      redirect_to question_path(@question,anchor: dom_id(@answer))
    else
      render :edit
    end
  end
  def edit

  end

  def create
    @answer = @question.answers.build answer_params

    if @answer.save
      flash[:success] = "Answer created"
      redirect_to question_path(@question)
    else

      @answers = @question.answers.order created_at: :desc

      render 'questions/show'
    end
  end

  def destroy

    @answer.destroy

    flash[:success] = "Answer deleted"
    redirect_to question_path(@question)
  end

  private

  def set_question!
    @question = Question.find params[:question_id]
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling

  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
  end

  def user_signed_in?
    current_user.present?
  end

  helper_method :current_user, :user_signed_in?
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound(exception)
      logger.warn exception
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show destroy edit update]

  def show
    @answer = @question.answers.build
    # @answers = Answer.where(question: @question).order created_at: :desc
    @answers = @question.answers.order(created_at: :desc).page(params[:page])
  end

  def destroy
    @question.destroy
    flash[:success] = "Question deleted!"
    redirect_to questions_path
  end

  def edit
  end

  def update
    if @question.update question_params
      flash[:success] = "Question updated!"
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @questions = Question.order(created_at: :desc).page params[:page]
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = "Question created!"
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the app, #{@user.name}"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? 'text-secondary' : 'text-white'

    options[:class] = if options[:class]
                        options[:class] + ' ' + css_class
                      else
                        css_class
                      end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: {current_page: current_page}
  end

  def full_title(page_title = "")
    base_title = "AskIt"
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'mb-3 card', id: dom_id(answer) do %>
  <div class="card-body">
    <section class="card-text">
      <small><time datetime="<%= answer.formatted_created_at %>">
        <%= answer.formatted_created_at %>
      </time></small>

      <div class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </div>
    </section>

    <%= link_to 'Edit', edit_question_answer_path(question, answer),
                class: 'btn btn-info btn-sm' %>
    <%= button_to 'Delete', question_answer_path(question, answer), class: 'btn btn-danger btn-sm',
                method: :delete %>
  </div>
<% end %>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit answer!", class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, 'Edit answer' %>


<h1>Edit answer</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application.bootstrap", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield :main_menu %>


  <main class="container mt-3">
    <% flash.each do |k,v| %>
      <%= tag.div v,class: "alert alert-#{k}", role: 'alert' %>
    <% end %>
    <%= yield %>
  </main>

  </body>
</html>

app/views/pages/index.html.erb
<% provide :page_title, 'Home' %>
<% currently_at 'Home' %>
<h1>Welcome to LearnRails</h1>

&copy; @Max Gerun <%= Time.now.year %>

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>

<%= form_with model:@question do |f| %>
  <div class="mb-3 row">
    <%= f.label :title,class: 'col-sm-2 col-form-label' %>

    <div class="col-sm-10">
      <%= f.text_field :title,  placeholder: "Title", class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :body, class: 'col-sm-2 col-form-label' %>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<% currently_at 'Edit' %>
<% provide :page_title, 'Edit question' %>

<h1 class="mb-4">Edit question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Questions</h1>

<%= link_to 'Create',new_question_path, class: 'btn btn-primary btn-lg' %>
<%= paginate @questions %>
<% @questions.each do |question| %>
  <article class="card mt-3">
    <div class="card-body">
      <h4><%= question.title %></h4>

      <section class="card-text">
        <time datetime="<%= question.formatted_created_at %>">
         <small><%= question.formatted_created_at %></small>
        </time>

        <p class="my-2">
          <%= truncate strip_tags(question.body), length: 150 %>
        </p>
      </section>

      <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary' %>
      <%= button_to "Destroy", question_path(question), class: 'btn btn-danger' ,method: :delete %>

    </div>
  </article>
<% end %>

<%= paginate @questions %>

app/views/questions/new.html.erb
<% currently_at 'Create' %>
<% provide :page_title, 'New question' %>

<h1 class="mb-4">New question</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<% provide :page_title, 'Show' %>
<% currently_at 'Show' %>

<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
  <%= @question.formatted_created_at %>
</time>

<div class="lead my-3">
  <%= sanitize @question.body %>
</div>

<%= link_to 'Show', question_path(@question), class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary' %>
<%= button_to 'Destroy', question_path(@question), class: 'btn btn-danger',method: :delete %>

<hr class="my-3">

<h2>Write your answer</h2>
<%= paginate @answers %>
<%= render 'answers/form' %>

<h2 class="mt-5">Answers</h2>

<%= render partial: 'answers/answer', collection: @answers,as: :answer,locals: {question: @question} %>
<%= paginate @answers %>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div  class="alert alert-danger">
    <ul class="mb-0">
      <%= object.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>

<header class="p-3 bg-dark text-white">
  <div class="container">
    <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-center">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= nav_tab 'Home', root_path, class: 'nav-link px-2', current_page: current_page%></li>
        <li><%= nav_tab 'Questions', questions_path, class: 'nav-link px-2', current_page: current_page %></li>
      </ul>

      <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
        <% if user_signed_in? %>
          <li>
            <a class="nav-link px-2 text-white" href="#"></a>
            <%= current_user.name %>
          </li>
        <% else %>
        <li>
          <%= nav_tab 'Sign Up', new_user_path,
          class: 'nav-link px-2', current_page: current_page%>
        </li>
          <% end %>
      </ul>
    </nav>
  </div>

</header>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user %>

<%= form_with model:@user do |f| %>
  <div class="mb-3 row">
    <%= f.label :email,class: 'col-sm-2 col-form-label' %>

    <div class="col-sm-10">
      <%= f.email_field :email,  placeholder: "E-mail", class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :name, class: 'col-sm-2 col-form-label' %>

    <div class="col-sm-10">
      <%= f.text_field :name, placeholder: "Name", class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>


    <div class="col-sm-10">
      <%= f.password_field :password, placeholder: "Password", class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation%>
    </div>


    <div class="col-sm-10">

        <%= f.password_field :password_confirmation, class: 'form-control form-control-lg' %>


    </div>
  </div>

  <%= f.submit "Register", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/users/new.html.erb
<% currently_at 'Registration' %>
<% provide :page_title, 'Sign Up' %>

<h1 class="mb-4">Registration</h1>

<%= render 'form' %>